name: Build Prizoop CG-100 g3a

on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.c"
      - "**/*.cpp"
      - "CMakeLists.txt"
      - ".github/workflows/build-g3a.yml"
      - "cmake/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install host dependencies (apt)
        shell: bash
        run: |
          set -euxo pipefail
          sudo apt-get update
          # Core build + pkg-config
          sudo apt-get install -y build-essential cmake pkg-config git python3 python3-pip
          # fxSDK deps discovered by CMake (png, usb, udisks2 -> glib/gio/gobject)
          sudo apt-get install -y libpng-dev libusb-1.0-0-dev libudisks2-dev libglib2.0-dev libgirepository1.0-dev
          # Optional but helpful
          sudo apt-get install -y libudev-dev
          # SuperH cross toolchain from Ubuntu (avoid building sh-elf-gcc ourselves)
          sudo apt-get install -y gcc-sh-elf binutils-sh-elf
          # Quick sanity checks (fail early if something’s missing)
          pkg-config --modversion libpng16
          pkg-config --modversion libusb-1.0
          pkg-config --modversion udisks2
          pkg-config --modversion gio-2.0
          pkg-config --modversion gobject-2.0
          pkg-config --modversion glib-2.0
          sh-elf-gcc --version

      - name: Fetch GiteaPC
        shell: bash
        run: |
          set -euxo pipefail
          git clone --depth 1 https://git.planet-casio.com/Lephenixnoir/giteapc /tmp/giteapc

      - name: Install fxSDK and gint (non-interactive)
        shell: bash
        run: |
          set -euxo pipefail
          # Ensure $HOME/.local/bin ends up on PATH for later steps
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          # Auto-confirm prompts from giteapc
          yes | python3 /tmp/giteapc/giteapc.py install Lephenixnoir/fxsdk
          yes | python3 /tmp/giteapc/giteapc.py install Lephenixnoir/gint
          # Verify tools are installed
          fxsdk --help >/dev/null
          fxconv --help >/dev/null || true

      - name: Build (.g3a) with fxSDK
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p build
          # Build for fx-CG (Prizm) using the fxSDK wrapper
          fxsdk build-fxcg --build-dir build

      - name: Upload g3a artifact
        uses: actions/upload-artifact@v4
        with:
          name: prizoop_cg100
          path: build/*.g3a
