name: Build Prizoop CG-100 g3a

on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.c"
      - "**/*.cpp"
      - "CMakeLists.txt"
      - ".github/workflows/build-g3a.yml"
      - "cmake/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install basic deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git python3 curl pkg-config gperf wget unzip bzip2

      # Install GiteaPC to ~/.local/bin non-interactively
      - name: Install GiteaPC
        run: |
          curl -fsSL https://git.planet-casio.com/Lephenixnoir/GiteaPC/raw/branch/master/install.sh -o /tmp/giteapc-install.sh
          bash /tmp/giteapc-install.sh --user
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          # sanity checks
          ls -al "$HOME/.local/bin" || true
          "$HOME/.local/bin/giteapc" --help || true

      - name: Install fxSDK & gint (via GiteaPC)
        run: |
          "$HOME/.local/bin/giteapc" install Lephenixnoir/fxsdk
          "$HOME/.local/bin/giteapc" install Lephenixnoir/gint
          # ensure fxsdk is on PATH for subsequent steps
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          "$HOME/.local/bin/fxsdk" --help || true

      - name: Build (.g3a)
        run: |
          mkdir -p build
          "$HOME/.local/bin/fxsdk" build-fxcg --build-dir build

      - name: Upload g3a artifact
        uses: actions/upload-artifact@v4
        with:
          name: prizoop_cg100
          path: build/*.g3a
