name: Build Prizoop CG-100 g3a

on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.c"
      - "**/*.cpp"
      - "CMakeLists.txt"
      - ".github/workflows/build-g3a.yml"
      - "cmake/**"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install system deps (no interactive prompts)
        shell: bash
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake git python3 pkg-config \
            libpng-dev libusb-1.0-0-dev libsdl2-dev \
            libudisks2-dev libglib2.0-dev libgirepository1.0-dev zlib1g-dev \
            gcc-sh-elf binutils-sh-elf libnewlib-sh-elf-dev \
            libmpfr-dev libmpc-dev libppl-dev
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          sh-elf-gcc --version

      - name: Fetch GiteaPC
        shell: bash
        run: |
          set -euxo pipefail
          git clone --depth 1 https://git.planet-casio.com/Lephenixnoir/giteapc /tmp/giteapc
          test -f /tmp/giteapc/giteapc.py

      - name: Install fxSDK and gint (non-interactive; no pipes)
        shell: bash
        run: |
          set -euxo pipefail
          python3 /tmp/giteapc/giteapc.py install Lephenixnoir/fxsdk <<< "y"
          python3 /tmp/giteapc/giteapc.py install Lephenixnoir/gint  <<< "y"
          fxsdk --help >/dev/null

      - name: Build (.g3a)
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p build
          fxsdk build-fxcg --build-dir build
          ls -lh build/*.g3a

      - name: Upload g3a artifact
        uses: actions/upload-artifact@v4
        with:
          name: prizoop_cg100
          path: build/*.g3a
