name: Build Prizoop CG-100 g3a

on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.c"
      - "**/*.cpp"
      - "CMakeLists.txt"
      - ".github/workflows/build-g3a.yml"
      - "cmake/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install build prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake git python3 curl pkg-config \
            gperf bison flex texinfo libgmp-dev libmpfr-dev libmpc-dev \
            wget unzip bzip2

      # Install GiteaPC by cloning; call it explicitly via python3 (no PATH reliance)
      - name: Fetch GiteaPC
        run: |
          git clone https://git.planet-casio.com/Lephenixnoir/giteapc /tmp/giteapc
          test -f /tmp/giteapc/giteapc

      - name: Install fxSDK & gint (via GiteaPC)
        run: |
          python3 /tmp/giteapc/giteapc install Lephenixnoir/fxsdk
          python3 /tmp/giteapc/giteapc install Lephenixnoir/gint
          # Verify fxSDK CLI was installed to ~/.local/bin
          ls -al "$HOME/.local/bin"
          "$HOME/.local/bin/fxsdk" --help

      - name: Build (.g3a)
        run: |
          mkdir -p build
          "$HOME/.local/bin/fxsdk" build-fxcg --build-dir build
          ls -lh build/*.g3a

      - name: Upload g3a artifact
        uses: actions/upload-artifact@v4
        with:
          name: prizoop_cg100
          path: build/*.g3a
