name: Build Prizoop CG-100 g3a

on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.c"
      - "**/*.cpp"
      - "CMakeLists.txt"
      - ".github/workflows/build-g3a.yml"
      - "cmake/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install build prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake git python3 curl pkg-config \
            gperf wget unzip bzip2

      - name: Fetch GiteaPC (retry + tarball fallback)
        run: |
          set -euxo pipefail
          for i in 1 2 3; do
            git clone --depth 1 https://git.planet-casio.com/Lephenixnoir/giteapc /tmp/giteapc && break || sleep 10
          done || true
          if [ ! -d /tmp/giteapc ]; then
            curl -fL https://git.planet-casio.com/Lephenixnoir/GiteaPC/archive/master.tar.gz -o /tmp/giteapc.tgz
            mkdir -p /tmp/giteapc
            tar -xzf /tmp/giteapc.tgz -C /tmp/giteapc --strip-components=1
          fi
          test -f /tmp/giteapc/giteapc.py

      - name: Install fxSDK & gint (via GiteaPC)
        run: |
          set -euxo pipefail
          python3 /tmp/giteapc/giteapc.py install Lephenixnoir/fxsdk
          python3 /tmp/giteapc/giteapc.py install Lephenixnoir/gint
          "$HOME/.local/bin/fxsdk" --help

      - name: Build (.g3a)
        run: |
          set -euxo pipefail
          mkdir -p build
          "$HOME/.local/bin/fxsdk" build-fxcg --build-dir build
          ls -lh build/*.g3a

      - name: Upload g3a artifact
        uses: actions/upload-artifact@v4
        with:
          name: prizoop_cg100
          path: build/*.g3a
