name: Build Prizoop CG-100 g3a

on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.c"
      - "**/*.cpp"
      - "CMakeLists.txt"
      - ".github/workflows/build-g3a.yml"
      - "cmake/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake git python3 pkg-config \
            libpng-dev libusb-1.0-0-dev libsdl2-dev \
            libudisks2-dev libglib2.0-dev libgirepository1.0-dev \
            zlib1g-dev \
            gcc-sh-elf binutils-sh-elf
          # Make sure local user bin is on PATH for tools fxSDK installs
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Fetch GiteaPC
        run: |
          set -euxo pipefail
          git clone https://git.planet-casio.com/Lephenixnoir/giteapc /tmp/giteapc

      - name: Install toolchain and SDKs with GiteaPC (non-interactive)
        run: |
          set -euxo pipefail
          yes | python3 /tmp/giteapc/giteapc.py install Lephenixnoir/sh-elf-gcc
          yes | python3 /tmp/giteapc/giteapc.py install Lephenixnoir/fxsdk
          yes | python3 /tmp/giteapc/giteapc.py install Lephenixnoir/gint
          "$HOME/.local/bin/fxsdk" --version || true
          "$HOME/.local/bin/fxsdk" --help    || true

      - name: Build (.g3a)
        run: |
          set -euxo pipefail
          mkdir -p build
          fxsdk build-fxcg --build-dir build

      - name: Upload g3a artifact
        uses: actions/upload-artifact@v4
        with:
          name: prizoop_cg100
          path: build/*.g3a
