name: Build G3A

on:
  push:            # runs on any push to any branch
  workflow_dispatch:  # lets you run it manually from Actions tab

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake git python3 pkg-config \
            libpng-dev libusb-1.0-0-dev libsdl2-dev libudisks2-dev \
            libglib2.0-dev libgirepository1.0-dev zlib1g-dev \
            gcc-sh-elf binutils-sh-elf libnewlib-sh-elf-dev \
            libmpfr-dev libmpc-dev libppl-dev

      - name: Get giteapc
        run: git clone --depth 1 https://git.planet-casio.com/Lephenixnoir/giteapc /tmp/giteapc

      - name: Install fxsdk & gint
        run: |
          python3 /tmp/giteapc/giteapc.py install Lephenixnoir/fxsdk
          python3 /tmp/giteapc/giteapc.py install Lephenixnoir/gint

      - name: Add fxsdk to PATH for later steps
        run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Sanity check
        run: |
          fxsdk --version
          sh-elf-gcc --version

      - name: Configure (FX-CG50)
        run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=$HOME/.local/lib/cmake/fxsdk/FXCG50.cmake

      - name: Build
        run: cmake --build build -j2

      - name: Locate g3a
        id: locate
        run: echo "file=$(find build -name '*.g3a' -print -quit)" >> "$GITHUB_OUTPUT"

      - name: Upload .g3a
        if: steps.locate.outputs.file != ''
        uses: actions/upload-artifact@v4
        with:
          name: g3a
          path: ${{ steps.locate.outputs.file }}
