name: Build Prizoop CG-100 g3a

on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.c"
      - "**/*.cpp"
      - "CMakeLists.txt"
      - ".github/workflows/build-g3a.yml"
      - "cmake/**"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 150

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install build prerequisites (with apt retries)
        shell: bash
        run: |
          set -Eeuo pipefail
          sudo apt-get update -o Acquire::Retries=5
          sudo apt-get install -y -o Acquire::Retries=5 \
            ca-certificates build-essential cmake git python3 curl pkg-config \
            gperf wget unzip bzip2 libpng-dev libusb-1.0-0-dev

      - name: Cache toolchains and installs
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/giteapc
            ~/.local/opt
            ~/.cache/giteapc
          key: gpc-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt','cmake/**') }}
          restore-keys: |
            gpc-${{ runner.os }}-

      - name: Fetch GiteaPC robustly (installer → clone → tarball), ensure `giteapc`
        shell: bash
        run: |
          set -Eeuo pipefail
          # 1) Installer
          curl -fsSL --retry 5 --retry-delay 5 --retry-all-errors \
            https://git.planet-casio.com/Lephenixnoir/GiteaPC/raw/branch/master/install.sh \
            -o /tmp/gpc_install.sh || true
          if [ -s /tmp/gpc_install.sh ]; then bash /tmp/gpc_install.sh --user || true; fi

          # 2) Clone (retries)
          if ! command -v giteapc >/dev/null 2>&1; then
            for i in 1 2 3 4 5; do
              git clone --depth 1 --filter=blob:none --single-branch \
                https://git.planet-casio.com/Lephenixnoir/giteapc /tmp/giteapc && break || sleep 10
            done || true
          fi

          # 3) Tarball fallback
          if ! command -v giteapc >/dev/null 2>&1 && [ ! -d /tmp/giteapc ]; then
            curl -fL --retry 5 --retry-delay 5 --retry-all-errors \
              https://git.planet-casio.com/Lephenixnoir/GiteaPC/archive/master.tar.gz \
              -o /tmp/giteapc.tgz
            mkdir -p /tmp/giteapc
            tar -xzf /tmp/giteapc.tgz -C /tmp/giteapc --strip-components=1
          fi

          # Wrapper if still not on PATH
          if ! command -v giteapc >/dev/null 2>&1; then
            test -f /tmp/giteapc/giteapc.py
            mkdir -p "$HOME/.local/bin"
            printf '#!/usr/bin/env bash\nexec python3 %q "$@"\n' "/tmp/giteapc/giteapc.py" > "$HOME/.local/bin/giteapc"
            chmod +x "$HOME/.local/bin/giteapc"
            echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          fi

          giteapc --help || true

      - name: Install sh-elf cross toolchain (non-interactive)
        shell: bash
        run: |
          set -Eeuo pipefail
          yes | giteapc install Lephenixnoir/sh-elf-gcc

      - name: Build & install fxSDK from GitHub mirror (UDisks2 disabled)
        shell: bash
        run: |
          set -Eeuo pipefail
          git clone --depth 1 https://github.com/Insoft-UK/fxSDK /tmp/fxsdk
          cmake -S /tmp/fxsdk -B /tmp/fxsdk-build \
            -DCMAKE_INSTALL_PREFIX="$HOME/.local" \
            -DFXLINK_DISABLE_UDISKS2=1
          cmake --build /tmp/fxsdk-build -j
          cmake --install /tmp/fxsdk-build
          "$HOME/.local/bin/fxsdk" --help

      - name: Build & install gint (GitHub fallback if forge fails)
        shell: bash
        run: |
          set -Eeuo pipefail
          for i in 1 2 3; do
            git clone --depth 1 https://git.planet-casio.com/Lephenixnoir/gint /tmp/gint && break || sleep 10
          done || true
          if [ ! -d /tmp/gint ]; then
            git clone --depth 1 https://github.com/Insoft-UK/gint /tmp/gint
          fi
          cmake -S /tmp/gint -B /tmp/gint-build \
            -DCMAKE_INSTALL_PREFIX="$HOME/.local"
          cmake --build /tmp/gint-build -j
          cmake --install /tmp/gint-build

      - name: Build (.g3a)
        shell: bash
        run: |
          set -Eeuo pipefail
          mkdir -p build
          "$HOME/.local/bin/fxsdk" build-fxcg --build-dir build
          ls -lh build/*.g3a

      - name: Upload g3a artifact
        uses: actions/upload-artifact@v4
        with:
          name: prizoop_cg100
          path: build/*.g3a
